language: scala
scala:
  - 2.11.2

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install lib32z1 || true
  - sudo apt-get -qq install lib32ncurses5 || true
  - sudo apt-get -qq install lib32bz2-1.0 || true
  - sudo apt-get -qq install lib32stdc++6 || true
  - sudo apt-get -qq install libopenal1 || true

before_script:
  - curl -L  http://sourceforge.net/projects/launch4j/files/launch4j-3/3.6/launch4j-3.6-linux.tgz/download > launch4j.tgz
  - tar xvzf launch4j.tgz
  - PATH=$PATH:$PWD/launch4j
  - sbt update-libs
  - sbt package

script: 
  - ./package/package.sh
